# Generated by Django 5.0.4 on 2024-05-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pais",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del país", max_length=30, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Paises",
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la provincia", max_length=30, unique=True
                    ),
                ),
                (
                    "pais",
                    models.ForeignKey(
                        help_text="País al que pertenece la provincia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.pais",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Provincias",
            },
        ),
        migrations.CreateModel(
            name="Aeropuerto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre del aeropuerto", max_length=30, unique=True
                    ),
                ),
                (
                    "codigo_iata",
                    models.CharField(
                        help_text="Código IATA del aeropuerto",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        help_text="Provincia donde está el aeropuerto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.provincia",
                    ),
                ),
            ],
        ),
    ]
