# Generated by Django 5.0.4 on 2024-05-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyandu", "0002_fabricante_alter_aeropuerto_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(help_text="Nombre de la categoría", max_length=30),
                ),
                (
                    "descripcion_categoria",
                    models.TextField(help_text="Descripción de la categoría"),
                ),
            ],
            options={
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "Otro")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Generos",
            },
        ),
        migrations.AlterModelOptions(
            name="aeropuerto",
            options={"verbose_name_plural": "Aeropuertos"},
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="Nombre y Apellido del empleado", max_length=60
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico del empleado", max_length=254
                    ),
                ),
                (
                    "telefono",
                    models.CharField(help_text="Teléfono del empleado", max_length=30),
                ),
                (
                    "dirección",
                    models.CharField(
                        help_text="Dirección donde reside el empleado", max_length=30
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        help_text="Localidad donde reside el empleado", max_length=30
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        help_text="Categoria del empleado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.categoria",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        help_text="Provincia donde reside el empleado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.provincia",
                    ),
                ),
                (
                    "genero",
                    models.ForeignKey(
                        help_text="Género con el que se autopersive el empleado",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.genero",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Empleados",
            },
        ),
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_vuelo",
                    models.DateField(
                        blank=True, help_text="Día en que comienza el vuelo", null=True
                    ),
                ),
                (
                    "hora_vuelo",
                    models.TimeField(
                        blank=True, help_text="Hora en que despega el vuelo", null=True
                    ),
                ),
                (
                    "avion_vuelo",
                    models.ForeignKey(
                        help_text="Avión que realiza el vuelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.avion",
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        help_text="Aeropuerto donde llega el vuelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="nyandu.aeropuerto",
                    ),
                ),
                (
                    "origen",
                    models.ForeignKey(
                        help_text="Aeropuerto donde sale el vuelo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nyandu.aeropuerto",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vuelos",
            },
        ),
    ]
