# Generated by Django 5.0.4 on 2024-05-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nyandu", "0003_categoria_genero_alter_aeropuerto_options_empleado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empleado",
            old_name="dirección",
            new_name="direccion",
        ),
    ]
