# Generated by Django 5.0.4 on 2024-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyandu", "0004_rename_dirección_empleado_direccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aeropuerto",
            name="codigo_iata",
            field=models.CharField(
                help_text="Código IATA del aeropuerto", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="pais",
            name="nombre",
            field=models.CharField(help_text="Nombre del país", max_length=30),
        ),
    ]
