# Generated by Django 5.0.4 on 2024-05-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nyandu", "0005_alter_aeropuerto_codigo_iata_alter_pais_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empleado",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="localidad",
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="provincia",
        ),
    ]
