# Generated by Django 5.0.4 on 2024-05-28 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nyandu", "0006_remove_empleado_categoria_remove_empleado_genero_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genero",
        ),
        migrations.AddField(
            model_name="empleado",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoria del empleado",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nyandu.categoria",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "Otro")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="localidad",
            field=models.CharField(
                blank=True,
                help_text="Localidad donde reside el empleado",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                help_text="Provincia donde reside el empleado",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nyandu.provincia",
            ),
        ),
    ]
